### ISSUE TITLE
Home assistant mqtt discovery

### ISSUE THREAD

**Issue by lubeda** [1technophile/OpenMQTTGateway#571]
on OMG 0.9.3 and HA 0.170 i get this error:

`Exception in async_discover_sensor when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'state_topic': 'home/OpenMQTTGateway/BTtoMQTT/DA9194EA92B4', 'name': 'MiBand-steps', 'unique_id': 'DA9194EA92B4-MiBand-steps', 'device_class': 'steps', 'value_template': '{{ value_json.steps | is_defined }}', 'unit_of_measurement': 'nb', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 81, in async_discover_sensor config = PLATFORM_SCHEMA(discovery_payload) File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: value is not allowed for dictionary value @ data['device_class']`

The discovery for the "gatewayBT" is working fine. i compiled my binary and enabled Zdiscovery in the user_config.h

**Comment by lubeda** [comment]
Well after some research i didn't find the real cause for this issue.
I Think there are some fixed device classes for sensor 
[HA device classes for sensors](https://www.home-assistant.io/integrations/sensor/#device-class)
all other then this predefined should be left off so, in my case i 
commented out the lines for the device class
```
 //if (device_class[0])
  //  sensor.set("dev_cla", device_class); //device_class

```
